Apply environment in deployment

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,12 +1,41 @@
 name: Release
 
 on:
+  push:
+    branches: [main, cl/dev]
   release:
     types: [published]
 
 jobs:
+  pre-deploy:
+    runs-on: ubuntu-latest
+    steps:
+      - id: set-up-environment
+        name: Set up environment
+        run: |
+          target_staging=${{ github.ref == 'refs/heads/cl/dev' }}
+          target_production=${{ startsWith(github.ref, 'refs/tags/') }}
+
+          if [[ "$target_staging" == "true" ]]; then
+            echo '::set-output name=environment::Staging'
+            exit 0
+          fi
+
+          if [[ "$target_production" == "true" ]]; then
+            echo '::set-output name=environment::Production'
+            exit 0
+          fi
+
+          echo "Encounter unknown situation. Abort."
+          exit 1
+    outputs:
+      environment: ${{ steps.set-up-environment.outputs.environment }}
+
   build-and-deploy:
     runs-on: ubuntu-latest
+    needs:
+      - pre-deploy
+    environment: ${{ needs.pre-deploy.outputs.environment }}
     steps:
       - uses: actions/checkout@v2
 
@@ -34,7 +63,7 @@ jobs:
           yarn install
           yarn build
 
-      - uses: JamesIves/github-pages-deploy-action@4.1.1
-        with:
-          branch: gh-pages
-          folder: build
+          #- uses: JamesIves/github-pages-deploy-action@4.1.1
+          #  with:
+          #    branch: gh-pages
+          #    folder: build
